name: Upload EC2 System Info to S3

on:
  push:
    branches:
      - main  # Trigger when changes are pushed to the main branch
  pull_request:
    branches:
      - main  # Trigger on PR to main

jobs:
  upload_to_s3:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 requests

      # Run the Python script
      - name: Run upload script
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'  # or your specific region
        run: |
          python upload_s3_python.py
